dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: k7P3HeOGcWpgkdZyzJy/mRiwIwl7C6J1CCqau0eLdQNmpwWDoiQNt5OEav7dCveQrbZ5TajC58uKUfhwh2gqrDv6PriyuLLwfvFrodYxkxM4tkZpHHPJnFC36DlmTdodAFeLQoEjWNiJfwzbBZhEMSooTMbuG2y/Ik+ahdIAvdptYcK02ettgjXtgiTpb5V562gFUDK2wfhrdwMtBoQAIYAJvdl5bfn3EIAXJWMIWbX/5KgD21/JXmORS5KrdayoPXrnVX/avJWlmjf1DZb5QuD363v005SQ9dNht1Beaba4T82RYp7Zl8BW+wYJGmwsWMsGvZeAXCBdQze14QP7ssD55PSz6nJACSFoN0xHnrdc4NxbrDU2K8KZDI/lTU3X3llAY2sRkk2/DFU4F/5cq8gHIZPxt+wsrOiIRpav9yHbfEbRtsZn8O8X6GTu/E42nTvvK5hL+3wKAFsZxWydI1FIH93IGKkaMVqI+5yYz3SckBk7PiCTM4wOnVdAH3clvNABxDDnUURyhYZvIVZu9JopRqdaZkkAI86JNk+p6GtCgD2xJObz5CbT1XbcIAAqDt930m4ulVPk+6Z0+mo3Frpm4Q+n/OGHHUJgdR2Sj+Zifq1RfJA+7+DT1L77ZnpCuR/BqRMKix41Q5FrG/kEgQMC9f3DgIYN9SN05n/ni64=
