version: '3.3'
services:

  post_db:
    env_file: .env
    image: mongo:${MONGO_IMAGE_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
          - ui_db


  ui:
    env_file: .env
    image: ${USERNAME}/ui:${UI_IMAGE_VERSION}
    ports:
      - ${UI_PORT}:${UI_PORT}/${UI_PROTOCOL}
    networks:
      - front_net

  post:
    env_file: .env
    image: ${USERNAME}/post:${POST_IMAGE_VERSION}
    networks:
      - back_net
      - front_net
  comment:
    env_file: .env
    image: ${USERNAME}/comment:${COMMENT_IMAGE_VERSION}
    networks:
      - back_net
      - front_net

      
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - front_net
      - prometheus

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - prometheus
volumes:
  prometheus_data:
  post_db:

networks:
  back_net:
  front_net:
  prometheus:
